# Generated by Django 6.0.3 on 2026-03-22 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers as a JSON object, e.g. {"Authorization": "Bearer token"}')),
                ('body', models.JSONField(blank=True, default=dict, help_text='Request body as a JSON object (used for POST/PUT/PATCH)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('cron', 'Cron')], default='interval', max_length=10)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Run every N seconds (used when schedule_type is "interval")', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression (minute hour day month weekday), e.g. "0 9 * * 1-5"', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False, help_text='Email the result after each run')),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated list of email addresses to notify')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='api.apiendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.FloatField(blank=True, help_text='Request round-trip time in milliseconds', null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.apiendpoint')),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='api.scheduledtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
