# Generated by Django 6.0.3 on 2026-03-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Extra HTTP headers as a JSON object. Authentication headers are managed separately via Credentials.'),
        ),
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key_header', 'API Key – Header'), ('api_key_query', 'API Key – Query Parameter'), ('basic', 'Basic Auth (Username & Password)'), ('custom_header', 'Custom Header')], default='none', help_text='Authentication method used when calling this endpoint', max_length=20)),
                ('token', models.CharField(blank=True, help_text='Bearer token, API key value, or custom header value', max_length=2000)),
                ('username', models.CharField(blank=True, help_text='Username for Basic Auth', max_length=500)),
                ('password', models.CharField(blank=True, help_text='Password for Basic Auth', max_length=500)),
                ('header_name', models.CharField(blank=True, default='Authorization', help_text='Header name for "API Key – Header" or "Custom Header" auth (defaults to "Authorization")', max_length=200)),
                ('query_param_name', models.CharField(blank=True, help_text='Query parameter name for "API Key – Query Parameter" auth', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='api.apiendpoint')),
            ],
            options={
                'verbose_name': 'API Credential',
            },
        ),
    ]
