# Generated by Django 6.0.3 on 2026-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apiendpoint_headers_apicredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='client_id',
            field=models.CharField(blank=True, help_text='OAuth 2.0 client ID', max_length=500),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='client_secret',
            field=models.CharField(blank=True, help_text='OAuth 2.0 client secret', max_length=2000),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='extra_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Additional HTTP headers applied on every request, merged after the primary auth headers.  Use for multi-header API keys, tenant IDs, versioning headers, etc.  Example: {"X-Tenant-ID": "acme", "X-API-Version": "2"}'),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='extra_query_params',
            field=models.JSONField(blank=True, default=dict, help_text='Additional query parameters applied on every request, merged after any primary auth query params.  Example: {"version": "2", "format": "json"}'),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='oauth2_scope',
            field=models.CharField(blank=True, help_text='Optional space-separated OAuth 2.0 scopes', max_length=500),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='token_url',
            field=models.URLField(blank=True, help_text='OAuth 2.0 token endpoint URL (e.g. https://auth.example.com/oauth/token)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('api_key_header', 'API Key – Header'), ('api_key_query', 'API Key – Query Parameter'), ('basic', 'Basic Auth (Username & Password)'), ('digest', 'Digest Auth (Username & Password)'), ('oauth2_client_credentials', 'OAuth 2.0 – Client Credentials'), ('custom_header', 'Custom Header')], default='none', help_text='Primary authentication method used when calling this endpoint', max_length=30),
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='password',
            field=models.CharField(blank=True, help_text='Password for Basic or Digest Auth', max_length=500),
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='username',
            field=models.CharField(blank=True, help_text='Username for Basic or Digest Auth', max_length=500),
        ),
    ]
